language: cpp
compiler:
  - clang
  - gcc
script:
  - cd matrix && rm storage_engine.h && ln -s storage_engine/vector.h storage_engine.h && cd ..
  - make clean compile test
  - cd matrix && rm storage_engine.h && ln -s storage_engine/array.h storage_engine.h && cd ..
  - make clean compile test
