#!/bin/bash
# Written by     : Chirantan Mitra

cd ../build
FILES=$(ls *_demo)

for file in $FILES
do
    echo -e "\nStart execute ${file}\n"
    ./${file}
    echo -e "\nFinish execute ${file}\n"
done

